### ISSUE TITLE
exporting model data to controllers through sequilize

### ISSUE THREAD

**Issue by SamGreenwood84** [Maximilian93B/DungeonsAndDevs#41]
Errors:
C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:8
        const territories = await Territory.findAll();
                            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\routes\api\getTerritories.js:4:31)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)

**Comment by SamGreenwood84** [comment]
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '../../Models/territory'
Require stack:
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\routes\api\getTerritories.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\routes\routes.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\controllers\\territoryController.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\routes\\api\\getTerritories.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\routes\\routes.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\server.js'
  ]
}

Node.js v20.10.0

sam@LAPTOP-UI20M2OO MINGW64 ~/Bootcamp/projects/02-project/DungeonsAndDevs (controllerbranch)
$ git pull origin main
Enter passphrase for key '/c/Users/sam/.ssh/id_ed25519': 
From github.com:Maximilian93B/DungeonsAndDevs
 * branch            main       -> FETCH_HEAD
Already up to date.

sam@LAPTOP-UI20M2OO MINGW64 ~/Bootcamp/projects/02-project/DungeonsAndDevs (controllerbranch)
$ node server.js
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '../../Models/territory'
Require stack:
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\routes\api\getTerritories.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\routes\routes.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\controllers\\territoryController.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\routes\\api\\getTerritories.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\routes\\routes.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\server.js'
  ]
}

**Comment by SamGreenwood84** [comment]
Current directory: C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '../../Models/territory'
Require stack:
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\routes\api\getTerritories.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\routes\routes.js
- C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:5:39)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\routes\api\getTerritories.js:4:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\controllers\\territoryController.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\routes\\api\\getTerritories.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\Develop\\routes\\routes.js',
    'C:\\Users\\sam\\Bootcamp\\projects\\02-project\\DungeonsAndDevs\\server.js'
  ]
}

**Comment by SamGreenwood84** [comment]
C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3
const sequilize = new sequilize (sequilize);
                  ^

ReferenceError: Cannot access 'sequilize' before initialization
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

**Comment by SamGreenwood84** [comment]
C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3
const sequilize = new sequilize (sequilize);
                  ^

ReferenceError: Cannot access 'sequilize' before initialization
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

**Comment by SamGreenwood84** [comment]
C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3
const sequilize = new Sequilize (sequilize);
                  ^

ReferenceError: Sequilize is not defined
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

**Comment by SamGreenwood84** [comment]
C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3
const sequilize = new sequilize (Sequilize);
                  ^

ReferenceError: Cannot access 'sequilize' before initialization
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

Node.js v20.10.0

sam@LAPTOP-UI20M2OO MINGW64 ~/Bootcamp/projects/02-project/DungeonsAndDevs (controllerbranch)
$ node server.js
C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3
const sequilize = new sequilize (Sequilize);
                  ^

ReferenceError: Cannot access 'sequilize' before initialization
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

**Comment by SamGreenwood84** [comment]
C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3
const Territory = require('./territory')(sequelize, Sequilize.DataTypes);
                                                    ^

ReferenceError: Sequilize is not defined
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:3:53)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

**Comment by SamGreenwood84** [comment]
C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:2
const Sequilize = require(sequilize);
                          ^

ReferenceError: sequilize is not defined
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\Models\models.js:2:27)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\sam\Bootcamp\projects\02-project\DungeonsAndDevs\Develop\controllers\territoryController.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

**Comment by SamGreenwood84** [comment]
We may at this point put the controllers on the Wishlist and stick with our routes that work as our route logic is not extensive.
